language: ruby
sudo: false
rvm:
- 2.5

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

jobs:
  include:
    - stage: test
      script:
      - bundle exec htmlproofer html --disable-external
